# Generated by Django 6.0.6 on 2026-07-07 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_emoji', models.CharField(blank=True, max_length=10)),
                ('svg_code', models.TextField(blank=True)),
                ('is_beginner_friendly', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('track_type', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('both', 'Web Development')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GameLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('initial_code', models.TextField()),
                ('expected_output', models.CharField(max_length=200)),
                ('difficulty', models.CharField(default='easy', max_length=50)),
                ('time_limit', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='LandingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=1)),
                ('svg_icon', models.TextField(blank=True, null=True)),
                ('is_wide', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LandingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_emoji', models.CharField(max_length=10)),
                ('order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='LandingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=5)),
                ('text', models.TextField()),
                ('author_initials', models.CharField(max_length=5)),
                ('author_name', models.CharField(max_length=50)),
                ('avatar_bg_color', models.CharField(default='#F7F7FB', max_length=20)),
                ('avatar_text_color', models.CharField(default='#1c1d35', max_length=20)),
                ('order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField()),
                ('timezone_label', models.CharField(default='Asia/Tashkent', max_length=50)),
                ('prerequisites', models.CharField(max_length=300)),
                ('host_name', models.CharField(max_length=100)),
                ('going_count', models.IntegerField(default=0)),
                ('is_past', models.BooleanField(default=False)),
                ('svg_badge', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_emoji', models.CharField(max_length=10)),
                ('order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TechTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon_content', models.CharField(max_length=20)),
                ('icon_color', models.CharField(default='#000000', max_length=20)),
                ('is_custom_bg', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('initial_code', models.TextField(blank=True)),
                ('expected_output', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=1)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_practice', models.BooleanField(default=False)),
                ('is_supercharge', models.BooleanField(default=False)),
                ('is_guided_project', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='app.module')),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_level', models.CharField(blank=True, max_length=50)),
                ('unlocked_game_levels', models.IntegerField(default=1)),
                ('xp', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=200)),
                ('is_pro', models.BooleanField(default=False)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('completed_lessons', models.ManyToManyField(blank=True, to='app.lesson')),
                ('earned_badges', models.ManyToManyField(blank=True, to='app.badge')),
                ('selected_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gamelevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'level')},
            },
        ),
    ]
