# Generated by Django 5.2.16 on 2026-07-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_achievement_id_alter_badge_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicetask',
            name='correct_option',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='practicetask',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='practicetask',
            name='task_type',
            field=models.CharField(choices=[('theory', 'Nazariya'), ('quiz', 'Test'), ('code', 'Kod yozish')], default='code', max_length=50),
        ),
    ]
