# Generated by Django 5.2.16 on 2026-07-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_practicetask_correct_option_practicetask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='coins_reward',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='lesson',
            name='correct_option',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lesson',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lesson',
            name='type',
            field=models.CharField(choices=[('theory', 'Theory'), ('test', 'Test'), ('code', 'Code Editor')], default='theory', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='xp_reward',
            field=models.IntegerField(default=10),
        ),
    ]
