# Generated by Django 5.2.16 on 2026-07-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_lesson_coins_reward_lesson_correct_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='current_step',
            field=models.CharField(choices=[('theory', 'Theory'), ('test', 'Test'), ('practice', 'Practice'), ('completed', 'Completed')], default='theory', max_length=20),
        ),
    ]
